require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CondicionesdepagosController do

  # This should return the minimal set of attributes required to create a valid
  # Condicionesdepago. As you add validations to Condicionesdepago, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nombre" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CondicionesdepagosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all condicionesdepagos as @condicionesdepagos" do
      condicionesdepago = Condicionesdepago.create! valid_attributes
      get :index, {}, valid_session
      assigns(:condicionesdepagos).should eq([condicionesdepago])
    end
  end

  describe "GET show" do
    it "assigns the requested condicionesdepago as @condicionesdepago" do
      condicionesdepago = Condicionesdepago.create! valid_attributes
      get :show, {:id => condicionesdepago.to_param}, valid_session
      assigns(:condicionesdepago).should eq(condicionesdepago)
    end
  end

  describe "GET new" do
    it "assigns a new condicionesdepago as @condicionesdepago" do
      get :new, {}, valid_session
      assigns(:condicionesdepago).should be_a_new(Condicionesdepago)
    end
  end

  describe "GET edit" do
    it "assigns the requested condicionesdepago as @condicionesdepago" do
      condicionesdepago = Condicionesdepago.create! valid_attributes
      get :edit, {:id => condicionesdepago.to_param}, valid_session
      assigns(:condicionesdepago).should eq(condicionesdepago)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Condicionesdepago" do
        expect {
          post :create, {:condicionesdepago => valid_attributes}, valid_session
        }.to change(Condicionesdepago, :count).by(1)
      end

      it "assigns a newly created condicionesdepago as @condicionesdepago" do
        post :create, {:condicionesdepago => valid_attributes}, valid_session
        assigns(:condicionesdepago).should be_a(Condicionesdepago)
        assigns(:condicionesdepago).should be_persisted
      end

      it "redirects to the created condicionesdepago" do
        post :create, {:condicionesdepago => valid_attributes}, valid_session
        response.should redirect_to(Condicionesdepago.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved condicionesdepago as @condicionesdepago" do
        # Trigger the behavior that occurs when invalid params are submitted
        Condicionesdepago.any_instance.stub(:save).and_return(false)
        post :create, {:condicionesdepago => { "nombre" => "invalid value" }}, valid_session
        assigns(:condicionesdepago).should be_a_new(Condicionesdepago)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Condicionesdepago.any_instance.stub(:save).and_return(false)
        post :create, {:condicionesdepago => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested condicionesdepago" do
        condicionesdepago = Condicionesdepago.create! valid_attributes
        # Assuming there are no other condicionesdepagos in the database, this
        # specifies that the Condicionesdepago created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Condicionesdepago.any_instance.should_receive(:update).with({ "nombre" => "MyString" })
        put :update, {:id => condicionesdepago.to_param, :condicionesdepago => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested condicionesdepago as @condicionesdepago" do
        condicionesdepago = Condicionesdepago.create! valid_attributes
        put :update, {:id => condicionesdepago.to_param, :condicionesdepago => valid_attributes}, valid_session
        assigns(:condicionesdepago).should eq(condicionesdepago)
      end

      it "redirects to the condicionesdepago" do
        condicionesdepago = Condicionesdepago.create! valid_attributes
        put :update, {:id => condicionesdepago.to_param, :condicionesdepago => valid_attributes}, valid_session
        response.should redirect_to(condicionesdepago)
      end
    end

    describe "with invalid params" do
      it "assigns the condicionesdepago as @condicionesdepago" do
        condicionesdepago = Condicionesdepago.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Condicionesdepago.any_instance.stub(:save).and_return(false)
        put :update, {:id => condicionesdepago.to_param, :condicionesdepago => { "nombre" => "invalid value" }}, valid_session
        assigns(:condicionesdepago).should eq(condicionesdepago)
      end

      it "re-renders the 'edit' template" do
        condicionesdepago = Condicionesdepago.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Condicionesdepago.any_instance.stub(:save).and_return(false)
        put :update, {:id => condicionesdepago.to_param, :condicionesdepago => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested condicionesdepago" do
      condicionesdepago = Condicionesdepago.create! valid_attributes
      expect {
        delete :destroy, {:id => condicionesdepago.to_param}, valid_session
      }.to change(Condicionesdepago, :count).by(-1)
    end

    it "redirects to the condicionesdepagos list" do
      condicionesdepago = Condicionesdepago.create! valid_attributes
      delete :destroy, {:id => condicionesdepago.to_param}, valid_session
      response.should redirect_to(condicionesdepagos_url)
    end
  end

end
