require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PreciosController do

  # This should return the minimal set of attributes required to create a valid
  # Precio. As you add validations to Precio, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "producto" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PreciosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all precios as @precios" do
      precio = Precio.create! valid_attributes
      get :index, {}, valid_session
      assigns(:precios).should eq([precio])
    end
  end

  describe "GET show" do
    it "assigns the requested precio as @precio" do
      precio = Precio.create! valid_attributes
      get :show, {:id => precio.to_param}, valid_session
      assigns(:precio).should eq(precio)
    end
  end

  describe "GET new" do
    it "assigns a new precio as @precio" do
      get :new, {}, valid_session
      assigns(:precio).should be_a_new(Precio)
    end
  end

  describe "GET edit" do
    it "assigns the requested precio as @precio" do
      precio = Precio.create! valid_attributes
      get :edit, {:id => precio.to_param}, valid_session
      assigns(:precio).should eq(precio)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Precio" do
        expect {
          post :create, {:precio => valid_attributes}, valid_session
        }.to change(Precio, :count).by(1)
      end

      it "assigns a newly created precio as @precio" do
        post :create, {:precio => valid_attributes}, valid_session
        assigns(:precio).should be_a(Precio)
        assigns(:precio).should be_persisted
      end

      it "redirects to the created precio" do
        post :create, {:precio => valid_attributes}, valid_session
        response.should redirect_to(Precio.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved precio as @precio" do
        # Trigger the behavior that occurs when invalid params are submitted
        Precio.any_instance.stub(:save).and_return(false)
        post :create, {:precio => { "producto" => "invalid value" }}, valid_session
        assigns(:precio).should be_a_new(Precio)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Precio.any_instance.stub(:save).and_return(false)
        post :create, {:precio => { "producto" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested precio" do
        precio = Precio.create! valid_attributes
        # Assuming there are no other precios in the database, this
        # specifies that the Precio created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Precio.any_instance.should_receive(:update).with({ "producto" => "" })
        put :update, {:id => precio.to_param, :precio => { "producto" => "" }}, valid_session
      end

      it "assigns the requested precio as @precio" do
        precio = Precio.create! valid_attributes
        put :update, {:id => precio.to_param, :precio => valid_attributes}, valid_session
        assigns(:precio).should eq(precio)
      end

      it "redirects to the precio" do
        precio = Precio.create! valid_attributes
        put :update, {:id => precio.to_param, :precio => valid_attributes}, valid_session
        response.should redirect_to(precio)
      end
    end

    describe "with invalid params" do
      it "assigns the precio as @precio" do
        precio = Precio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Precio.any_instance.stub(:save).and_return(false)
        put :update, {:id => precio.to_param, :precio => { "producto" => "invalid value" }}, valid_session
        assigns(:precio).should eq(precio)
      end

      it "re-renders the 'edit' template" do
        precio = Precio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Precio.any_instance.stub(:save).and_return(false)
        put :update, {:id => precio.to_param, :precio => { "producto" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested precio" do
      precio = Precio.create! valid_attributes
      expect {
        delete :destroy, {:id => precio.to_param}, valid_session
      }.to change(Precio, :count).by(-1)
    end

    it "redirects to the precios list" do
      precio = Precio.create! valid_attributes
      delete :destroy, {:id => precio.to_param}, valid_session
      response.should redirect_to(precios_url)
    end
  end

end
