require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RetencionesController do

  # This should return the minimal set of attributes required to create a valid
  # Retencion. As you add validations to Retencion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "tipo" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RetencionesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all retenciones as @retenciones" do
      retencion = Retencion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:retenciones).should eq([retencion])
    end
  end

  describe "GET show" do
    it "assigns the requested retencion as @retencion" do
      retencion = Retencion.create! valid_attributes
      get :show, {:id => retencion.to_param}, valid_session
      assigns(:retencion).should eq(retencion)
    end
  end

  describe "GET new" do
    it "assigns a new retencion as @retencion" do
      get :new, {}, valid_session
      assigns(:retencion).should be_a_new(Retencion)
    end
  end

  describe "GET edit" do
    it "assigns the requested retencion as @retencion" do
      retencion = Retencion.create! valid_attributes
      get :edit, {:id => retencion.to_param}, valid_session
      assigns(:retencion).should eq(retencion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Retencion" do
        expect {
          post :create, {:retencion => valid_attributes}, valid_session
        }.to change(Retencion, :count).by(1)
      end

      it "assigns a newly created retencion as @retencion" do
        post :create, {:retencion => valid_attributes}, valid_session
        assigns(:retencion).should be_a(Retencion)
        assigns(:retencion).should be_persisted
      end

      it "redirects to the created retencion" do
        post :create, {:retencion => valid_attributes}, valid_session
        response.should redirect_to(Retencion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved retencion as @retencion" do
        # Trigger the behavior that occurs when invalid params are submitted
        Retencion.any_instance.stub(:save).and_return(false)
        post :create, {:retencion => { "tipo" => "invalid value" }}, valid_session
        assigns(:retencion).should be_a_new(Retencion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Retencion.any_instance.stub(:save).and_return(false)
        post :create, {:retencion => { "tipo" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested retencion" do
        retencion = Retencion.create! valid_attributes
        # Assuming there are no other retenciones in the database, this
        # specifies that the Retencion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Retencion.any_instance.should_receive(:update).with({ "tipo" => "MyString" })
        put :update, {:id => retencion.to_param, :retencion => { "tipo" => "MyString" }}, valid_session
      end

      it "assigns the requested retencion as @retencion" do
        retencion = Retencion.create! valid_attributes
        put :update, {:id => retencion.to_param, :retencion => valid_attributes}, valid_session
        assigns(:retencion).should eq(retencion)
      end

      it "redirects to the retencion" do
        retencion = Retencion.create! valid_attributes
        put :update, {:id => retencion.to_param, :retencion => valid_attributes}, valid_session
        response.should redirect_to(retencion)
      end
    end

    describe "with invalid params" do
      it "assigns the retencion as @retencion" do
        retencion = Retencion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Retencion.any_instance.stub(:save).and_return(false)
        put :update, {:id => retencion.to_param, :retencion => { "tipo" => "invalid value" }}, valid_session
        assigns(:retencion).should eq(retencion)
      end

      it "re-renders the 'edit' template" do
        retencion = Retencion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Retencion.any_instance.stub(:save).and_return(false)
        put :update, {:id => retencion.to_param, :retencion => { "tipo" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested retencion" do
      retencion = Retencion.create! valid_attributes
      expect {
        delete :destroy, {:id => retencion.to_param}, valid_session
      }.to change(Retencion, :count).by(-1)
    end

    it "redirects to the retenciones list" do
      retencion = Retencion.create! valid_attributes
      delete :destroy, {:id => retencion.to_param}, valid_session
      response.should redirect_to(retenciones_url)
    end
  end

end
