require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TrasladosController do

  # This should return the minimal set of attributes required to create a valid
  # Traslado. As you add validations to Traslado, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "tipo" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TrasladosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all traslados as @traslados" do
      traslado = Traslado.create! valid_attributes
      get :index, {}, valid_session
      assigns(:traslados).should eq([traslado])
    end
  end

  describe "GET show" do
    it "assigns the requested traslado as @traslado" do
      traslado = Traslado.create! valid_attributes
      get :show, {:id => traslado.to_param}, valid_session
      assigns(:traslado).should eq(traslado)
    end
  end

  describe "GET new" do
    it "assigns a new traslado as @traslado" do
      get :new, {}, valid_session
      assigns(:traslado).should be_a_new(Traslado)
    end
  end

  describe "GET edit" do
    it "assigns the requested traslado as @traslado" do
      traslado = Traslado.create! valid_attributes
      get :edit, {:id => traslado.to_param}, valid_session
      assigns(:traslado).should eq(traslado)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Traslado" do
        expect {
          post :create, {:traslado => valid_attributes}, valid_session
        }.to change(Traslado, :count).by(1)
      end

      it "assigns a newly created traslado as @traslado" do
        post :create, {:traslado => valid_attributes}, valid_session
        assigns(:traslado).should be_a(Traslado)
        assigns(:traslado).should be_persisted
      end

      it "redirects to the created traslado" do
        post :create, {:traslado => valid_attributes}, valid_session
        response.should redirect_to(Traslado.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved traslado as @traslado" do
        # Trigger the behavior that occurs when invalid params are submitted
        Traslado.any_instance.stub(:save).and_return(false)
        post :create, {:traslado => { "tipo" => "invalid value" }}, valid_session
        assigns(:traslado).should be_a_new(Traslado)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Traslado.any_instance.stub(:save).and_return(false)
        post :create, {:traslado => { "tipo" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested traslado" do
        traslado = Traslado.create! valid_attributes
        # Assuming there are no other traslados in the database, this
        # specifies that the Traslado created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Traslado.any_instance.should_receive(:update).with({ "tipo" => "MyString" })
        put :update, {:id => traslado.to_param, :traslado => { "tipo" => "MyString" }}, valid_session
      end

      it "assigns the requested traslado as @traslado" do
        traslado = Traslado.create! valid_attributes
        put :update, {:id => traslado.to_param, :traslado => valid_attributes}, valid_session
        assigns(:traslado).should eq(traslado)
      end

      it "redirects to the traslado" do
        traslado = Traslado.create! valid_attributes
        put :update, {:id => traslado.to_param, :traslado => valid_attributes}, valid_session
        response.should redirect_to(traslado)
      end
    end

    describe "with invalid params" do
      it "assigns the traslado as @traslado" do
        traslado = Traslado.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Traslado.any_instance.stub(:save).and_return(false)
        put :update, {:id => traslado.to_param, :traslado => { "tipo" => "invalid value" }}, valid_session
        assigns(:traslado).should eq(traslado)
      end

      it "re-renders the 'edit' template" do
        traslado = Traslado.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Traslado.any_instance.stub(:save).and_return(false)
        put :update, {:id => traslado.to_param, :traslado => { "tipo" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested traslado" do
      traslado = Traslado.create! valid_attributes
      expect {
        delete :destroy, {:id => traslado.to_param}, valid_session
      }.to change(Traslado, :count).by(-1)
    end

    it "redirects to the traslados list" do
      traslado = Traslado.create! valid_attributes
      delete :destroy, {:id => traslado.to_param}, valid_session
      response.should redirect_to(traslados_url)
    end
  end

end
